server:
  port: 8000

spring:
  application:
    name: client-app
  profiles:
    active: dev
  security:
    user:
      name: client-user
      password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.188:8848
        namespace: public
        group: DEFAULT_GROUP
        metadata:
          user.name: client-user
          user.password: 123456

# 必须暴露 Actuator 端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always